/**
 * The output files, as pure functions of the export: source in, string out.
 *
 * Style Dictionary has no idea of a mode, and only 51 of the 97 semantic
 * tokens differ between light and dark. These formats emit the other 46 once,
 * so the dark block carries only what changes.
 */
import { at, dtcgType, leaves, modes, refVar, sysVar, withUnit } from './dtcg.mjs';

/** Splits the semantic tier into what themes and what does not. */
export function partition(src) {
  const refLines = [];
  for (const [path, value] of leaves(src.ref)) {
    refLines.push([refVar('ref.' + path.join('.')), withUnit(dtcgType('ref', path), value)]);
  }
  const light = [],
    dark = [],
    statics = [];
  for (const [path, value] of leaves(src.sys)) {
    const name = sysVar(path.join('.'));
    const m = modes(src, `sys.${path.join('.')}`, value);
    // a token whose two modes point at the same primitive does not theme
    if (m.light === m.dark) statics.push([name, `var(${refVar(m.light)})`]);
    else {
      light.push([name, `var(${refVar(m.light)})`]);
      dark.push([name, `var(${refVar(m.dark)})`]);
    }
  }
  const elevation = Object.entries(src.ref.elevation ?? {}).map(([lvl, g]) => {
    if (!at(src, `sys.shadow.${lvl}`))
      throw new Error(`ref.elevation.${lvl} has no sys.shadow.${lvl}`);
    return [`--wu-elevation-${lvl}`, `0 ${g.y}px ${g.blur}px 0 var(--wu-shadow-${lvl})`];
  });
  const typography = Object.entries(src.$typography ?? {}).map(([name, t]) => {
    if (!src.sys.type?.[t.role]) throw new Error(`$typography "${name}": unknown role "${t.role}"`);
    if (!src.ref['font-family']?.[t.family])
      throw new Error(`$typography "${name}": unknown family "${t.family}"`);
    const slug = name.toLowerCase().replace(/[^a-z0-9]+/g, '-');
    return [
      `--wu-font-${slug}`,
      `${t.weight} var(--wu-type-${t.role}-size)/var(--wu-type-${t.role}-line) var(--wu-ref-font-family-${t.family}), system-ui, sans-serif`,
    ];
  });
  return { refLines, light, dark, statics, elevation, typography };
}

const decl = (pairs, indent = '  ') => pairs.map(([k, v]) => `${indent}${k}: ${v};`).join('\n');

/**
 * Custom properties in both modes. Each theme block redeclares the elevation
 * composites because var() resolves where a property is declared, so a
 * composite declared once on :root keeps the root's shadow in a nested scope.
 */
export function css(src) {
  const p = partition(src);
  return `/* GENERATED by scripts/build-tokens.mjs — do not edit by hand.
   Source: ${src.$meta.source}
   Names match codeSyntax.WEB on the Figma variables, one for one. */

:root {
  /* ---- reference tier: raw values, rarely consumed directly ---- */
${decl(p.refLines)}

  /* ---- system tier: mode-invariant ---- */
${decl(p.statics)}

  /* ---- typography roles ---- */
${decl(p.typography)}
}

/* ---- system tier: light, on the root and on any nested light scope ---- */
:root,
[data-theme='light'] {
  color-scheme: light;

${decl(p.light)}

  /* ---- composite ---- */
${decl(p.elevation)}
}

[data-theme='dark'] {
  color-scheme: dark;

${decl(p.dark)}

${decl(p.elevation)}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
    color-scheme: dark;

${decl(p.dark, '    ')}

${decl(p.elevation, '    ')}
  }
}
`;
}

/** SCSS authoring vars. They point AT the custom properties, so a component
    written against them keeps theming when the attribute on <html> flips. */
export function scss(src) {
  const p = partition(src);
  const one = (pairs) => pairs.map(([k]) => `$${k.replace(/^--/, '')}: var(${k});`).join('\n');
  const names = [...p.statics, ...p.light].map(([k]) => k.replace(/^--wu-/, ''));
  return `// GENERATED by scripts/build-tokens.mjs — do not edit by hand.
// Source: ${src.$meta.source}
//
// Every variable here resolves to a CSS custom property rather than a literal.
// That is the point: a component written against $wu-text-primary keeps theming
// when the attribute on <html> flips, and a component written against #000000
// does not.

${one(p.refLines)}

${one(p.statics)}

${one(p.light)}

${one(p.typography)}

${one(p.elevation)}

// Every semantic token, by name, for iteration in docs and tests.
$wu-semantic-tokens: (
${names.map((n) => `  '${n}': var(--wu-${n})`).join(',\n')}
);
`;
}

/** Typed names for TS-side use and Storybook controls. */
export function ts(src) {
  const p = partition(src);
  const entry = ([k]) => `  '${k.replace(/^--wu-/, '')}': 'var(${k})',`;
  const sem = [...p.statics, ...p.light];
  return `// GENERATED by scripts/build-tokens.mjs — do not edit by hand.
// Source: ${src.$meta.source}

/** Every semantic token, mapped to the custom property that carries it. */
export const tokens = {
${sem.map(entry).join('\n')}
} as const;

/** Every primitive. Reach for a semantic token first — these are the ramp. */
export const ref = {
${p.refLines.map(entry).join('\n')}
} as const;

export type TokenName = keyof typeof tokens;
export type RefName = keyof typeof ref;

/** The two modes this system ships. */
export const modes = ['light', 'dark'] as const;
export type Mode = (typeof modes)[number];

/** ${sem.length} semantic tokens, ${p.refLines.length} primitives, ${p.dark.length} of which theme. */
export const counts = { semantic: ${sem.length}, ref: ${p.refLines.length}, themed: ${p.dark.length} } as const;
`;
}

/** The same functions, in the shape Style Dictionary registers. */
export const formats = (src) => ({
  'wu/css': () => css(src),
  'wu/scss': () => scss(src),
  'wu/ts': () => ts(src),
});
