/**
 * tokens/figma-export.json -> every file that consumes it.
 *
 *   node scripts/build-tokens.mjs
 *
 * The thin, side-effecting half of the pipeline: validate, then write. What
 * each file contains is decided by the pure functions in scripts/tokens/, which
 * tests/tokens.test.mjs exercises without touching the disk. Any broken rule
 * exits non-zero before a file is written.
 */
import StyleDictionary from 'style-dictionary';
import { copyFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { buildDtcg, loadSource, ROOT, SOURCE, validateSource } from './tokens/dtcg.mjs';
import { formats, partition } from './tokens/formats.mjs';

const ANGULAR = 'angular/src/tokens/';
const PUBLIC = 'public/artifacts/';
// absolute, because Style Dictionary resolves buildPath against the cwd and the
// Angular workspace runs this script from angular/; forward slashes for its posix join
const out = (dir) => join(ROOT, dir).replaceAll('\\', '/') + '/';

try {
  const src = loadSource();
  const c = validateSource(src);
  const dtcg = buildDtcg(src);

  for (const [name, format] of Object.entries(formats(src))) {
    StyleDictionary.registerFormat({ name, format });
  }
  for (const dir of ['app', 'tokens', ANGULAR, PUBLIC])
    mkdirSync(join(ROOT, dir), { recursive: true });

  // Style Dictionary parses the tree and resolves every {ref.*} before a byte is written
  const sd = new StyleDictionary({
    tokens: dtcg,
    log: { errors: { brokenReferences: 'throw' } },
    platforms: {
      web: {
        transformGroup: 'css',
        buildPath: out('app'),
        files: [{ destination: 'tokens.css', format: 'wu/css' }],
      },
      angular: {
        transformGroup: 'css',
        buildPath: out(ANGULAR),
        files: [
          { destination: 'tokens.css', format: 'wu/css' },
          { destination: '_tokens.scss', format: 'wu/scss' },
          { destination: 'tokens.ts', format: 'wu/ts' },
        ],
      },
    },
  });
  await sd.hasInitialized;
  await sd.buildAllPlatforms();

  // written from the source tree, not Style Dictionary's resolved one, so references stay intact
  writeFileSync(join(ROOT, 'tokens/tokens.json'), JSON.stringify(dtcg, null, 2) + '\n');

  // downloadable copies for /handoff, regenerated by the same command so they cannot go stale
  const artifacts = [
    [
      'tokens/tokens.json',
      'tokens.json',
      'DTCG-style JSON, references intact, values as CSS strings',
      'any platform',
    ],
    ['app/tokens.css', 'tokens.css', 'CSS custom properties, both modes', 'web'],
    [
      `${ANGULAR}_tokens.scss`,
      '_tokens.scss',
      'SCSS variables that resolve to the properties',
      'angular · scss',
    ],
    [
      `${ANGULAR}tokens.ts`,
      'tokens.ts',
      'Typed token names for TS and Storybook controls',
      'angular · typescript',
    ],
    [
      SOURCE,
      'figma-export.json',
      'The Figma variables export, the source everything else derives from',
      'source',
    ],
  ];
  const outputs = artifacts.map(([from, to, what, platform]) => {
    copyFileSync(join(ROOT, from), join(ROOT, PUBLIC, to));
    return { file: to, from, what, platform, href: `/artifacts/${to}` };
  });

  const p = partition(src);
  const manifest = {
    // the export date, not the build time, so two builds of one export are identical
    generated: src.$meta.exportedAt,
    source: SOURCE,
    counts: { ...c, themed: p.light.length, static: p.statics.length },
    outputs,
  };
  writeFileSync(join(ROOT, PUBLIC, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');

  console.log(
    `\ntokens.json  ${c.ref} ref + ${c.sys} sys (matches $meta.counts)\n` +
      `tokens.css   ${p.refLines.length} ref vars, ${p.statics.length} static, ${p.light.length} themed (x2), ${p.elevation.length} composite, ${p.typography.length} type roles\n` +
      `angular      _tokens.scss, tokens.css, tokens.ts -> ${ANGULAR}`
  );
} catch (e) {
  console.error(`\ntokens: build failed\n${e.message}`);
  process.exit(1);
}
